# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(678, 582)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.splitter = QtWidgets.QSplitter(self.centralWidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox_2 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableTestpaper = QtWidgets.QTableWidget(self.groupBox_2)
        self.tableTestpaper.setMinimumSize(QtCore.QSize(0, 100))
        self.tableTestpaper.setObjectName("tableTestpaper")
        self.tableTestpaper.setColumnCount(0)
        self.tableTestpaper.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableTestpaper)
        self.groupBox_3 = QtWidgets.QGroupBox(self.splitter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pteResults = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.pteResults.setObjectName("pteResults")
        self.verticalLayout_2.addWidget(self.pteResults)
        self.verticalLayout_4.addWidget(self.splitter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.labelMarkName = QtWidgets.QLabel(self.centralWidget)
        self.labelMarkName.setObjectName("labelMarkName")
        self.gridLayout_2.addWidget(self.labelMarkName, 0, 2, 1, 1)
        self.labelTotalMark = QtWidgets.QLabel(self.centralWidget)
        self.labelTotalMark.setObjectName("labelTotalMark")
        self.gridLayout_2.addWidget(self.labelTotalMark, 0, 3, 1, 1)
        self.labelTimeName = QtWidgets.QLabel(self.centralWidget)
        self.labelTimeName.setObjectName("labelTimeName")
        self.gridLayout_2.addWidget(self.labelTimeName, 1, 2, 1, 1)
        self.labelTime = QtWidgets.QLabel(self.centralWidget)
        self.labelTime.setObjectName("labelTime")
        self.gridLayout_2.addWidget(self.labelTime, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.cmbDifficulty = QtWidgets.QComboBox(self.centralWidget)
        self.cmbDifficulty.setObjectName("cmbDifficulty")
        self.gridLayout_2.addWidget(self.cmbDifficulty, 0, 1, 1, 1)
        self.cmbMode = QtWidgets.QComboBox(self.centralWidget)
        self.cmbMode.setObjectName("cmbMode")
        self.gridLayout_2.addWidget(self.cmbMode, 1, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnNew = QtWidgets.QPushButton(self.centralWidget)
        self.btnNew.setObjectName("btnNew")
        self.gridLayout.addWidget(self.btnNew, 0, 2, 1, 1)
        self.btnReset = QtWidgets.QPushButton(self.centralWidget)
        self.btnReset.setObjectName("btnReset")
        self.gridLayout.addWidget(self.btnReset, 0, 3, 1, 1)
        self.btnQuit = QtWidgets.QPushButton(self.centralWidget)
        self.btnQuit.setObjectName("btnQuit")
        self.gridLayout.addWidget(self.btnQuit, 1, 5, 1, 1)
        self.btnStop = QtWidgets.QPushButton(self.centralWidget)
        self.btnStop.setObjectName("btnStop")
        self.gridLayout.addWidget(self.btnStop, 1, 2, 1, 1)
        self.btnMark = QtWidgets.QPushButton(self.centralWidget)
        self.btnMark.setObjectName("btnMark")
        self.gridLayout.addWidget(self.btnMark, 1, 3, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.centralWidget)
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 1, 4, 1, 1)
        self.btnOpen = QtWidgets.QPushButton(self.centralWidget)
        self.btnOpen.setObjectName("btnOpen")
        self.gridLayout.addWidget(self.btnOpen, 0, 4, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 678, 25))
        self.menuBar.setObjectName("menuBar")
        self.menuNew_Test = QtWidgets.QMenu(self.menuBar)
        self.menuNew_Test.setObjectName("menuNew_Test")
        self.menuOptions = QtWidgets.QMenu(self.menuBar)
        self.menuOptions.setObjectName("menuOptions")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionNew_Test = QtWidgets.QAction(MainWindow)
        self.actionNew_Test.setObjectName("actionNew_Test")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionMark = QtWidgets.QAction(MainWindow)
        self.actionMark.setObjectName("actionMark")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionRegister = QtWidgets.QAction(MainWindow)
        self.actionRegister.setObjectName("actionRegister")
        self.menuNew_Test.addAction(self.actionNew_Test)
        self.menuNew_Test.addAction(self.actionOpen)
        self.menuNew_Test.addAction(self.actionReset)
        self.menuNew_Test.addAction(self.actionMark)
        self.menuNew_Test.addAction(self.actionSave)
        self.menuNew_Test.addSeparator()
        self.menuNew_Test.addAction(self.actionQuit)
        self.menuOptions.addAction(self.actionPreferences)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionRegister)
        self.menuBar.addAction(self.menuNew_Test.menuAction())
        self.menuBar.addAction(self.menuOptions.menuAction())
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AESOPS"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Test Paper"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Results"))
        self.labelMarkName.setText(_translate("MainWindow", "Marks: "))
        self.labelTotalMark.setText(_translate("MainWindow", "TextLabel"))
        self.labelTimeName.setText(_translate("MainWindow", "Time:  "))
        self.labelTime.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "Mode"))
        self.label.setText(_translate("MainWindow", "Difficulty"))
        self.btnNew.setText(_translate("MainWindow", "New"))
        self.btnReset.setText(_translate("MainWindow", "Reset"))
        self.btnQuit.setText(_translate("MainWindow", "Quit"))
        self.btnStop.setText(_translate("MainWindow", "Stop"))
        self.btnMark.setText(_translate("MainWindow", "Mark"))
        self.btnSave.setText(_translate("MainWindow", "Save"))
        self.btnOpen.setText(_translate("MainWindow", "Open"))
        self.menuNew_Test.setTitle(_translate("MainWindow", "Tests"))
        self.menuOptions.setTitle(_translate("MainWindow", "Options"))
        self.menuAbout.setTitle(_translate("MainWindow", "&Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPreferences.setShortcut(_translate("MainWindow", "Alt+P"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "F1"))
        self.actionNew_Test.setText(_translate("MainWindow", "New Test"))
        self.actionNew_Test.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionMark.setText(_translate("MainWindow", "Mark"))
        self.actionMark.setShortcut(_translate("MainWindow", "Ctrl+M"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionRegister.setText(_translate("MainWindow", "Register"))

