# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preference.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogPreference(object):
    def setupUi(self, DialogPreference):
        DialogPreference.setObjectName("DialogPreference")
        DialogPreference.resize(479, 347)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogPreference)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(DialogPreference)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.leNOperands = QtWidgets.QLineEdit(self.groupBox)
        self.leNOperands.setObjectName("leNOperands")
        self.gridLayout.addWidget(self.leNOperands, 2, 1, 1, 1)
        self.leTestNum = QtWidgets.QLineEdit(self.groupBox)
        self.leTestNum.setObjectName("leTestNum")
        self.gridLayout.addWidget(self.leTestNum, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.leDigits = QtWidgets.QLineEdit(self.groupBox)
        self.leDigits.setObjectName("leDigits")
        self.gridLayout.addWidget(self.leDigits, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.leNDataColumn = QtWidgets.QLineEdit(self.groupBox)
        self.leNDataColumn.setObjectName("leNDataColumn")
        self.gridLayout.addWidget(self.leNDataColumn, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(DialogPreference)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.rbtnTimer = QtWidgets.QRadioButton(self.groupBox_2)
        self.rbtnTimer.setObjectName("rbtnTimer")
        self.gridLayout_2.addWidget(self.rbtnTimer, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnApply = QtWidgets.QPushButton(DialogPreference)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnApply.sizePolicy().hasHeightForWidth())
        self.btnApply.setSizePolicy(sizePolicy)
        self.btnApply.setObjectName("btnApply")
        self.horizontalLayout.addWidget(self.btnApply)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogPreference)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.label_2.setBuddy(self.leTestNum)
        self.label.setBuddy(self.leDigits)
        self.label_5.setBuddy(self.leNOperands)
        self.label_4.setBuddy(self.leNDataColumn)

        self.retranslateUi(DialogPreference)
        self.buttonBox.accepted.connect(DialogPreference.accept)
        self.buttonBox.rejected.connect(DialogPreference.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogPreference)
        DialogPreference.setTabOrder(self.leDigits, self.leTestNum)
        DialogPreference.setTabOrder(self.leTestNum, self.leNOperands)
        DialogPreference.setTabOrder(self.leNOperands, self.rbtnTimer)
        DialogPreference.setTabOrder(self.rbtnTimer, self.btnApply)

    def retranslateUi(self, DialogPreference):
        _translate = QtCore.QCoreApplication.translate
        DialogPreference.setWindowTitle(_translate("DialogPreference", "Preference"))
        self.groupBox.setTitle(_translate("DialogPreference", "Options"))
        self.label_2.setText(_translate("DialogPreference", "How many tests? "))
        self.label.setText(_translate("DialogPreference", "Digits"))
        self.label_5.setText(_translate("DialogPreference", "Operands"))
        self.label_4.setText(_translate("DialogPreference", "Data Column"))
        self.groupBox_2.setTitle(_translate("DialogPreference", "Misc"))
        self.rbtnTimer.setText(_translate("DialogPreference", "Timer"))
        self.btnApply.setText(_translate("DialogPreference", "Apply"))

